# =============================================================================
# USER SERVICE CONFIG  (port 9001)
# =============================================================================
# Fetched ONLY by job-portal-user-service from Config Server.
# Common settings (eureka, jpa, resilience4j) come from application.yml.
# =============================================================================

server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_portal_user
    username: postgres
    password: $7090Ashok
    driver-class-name: org.postgresql.Driver

  # ── Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  (must match gateway)
jwt:
  secret: asdfghjklpoiuytrewqzxcvbnmlkjhglpouhggfdsawqwertyyuiioplmnbvcxzasdfgh
  expiration-ms: 86400000    # 24 hours